const List<String> motivationalTextsEn = [
  "Small steps build big confidence.",
  "Speak up, even if your voice shakes.",
  "Consistency beats motivation.",
  "Courage starts with one small action.",
  "Growth begins outside your comfort zone.",
  "Progress, not perfection.",
  "Listen more, talk smarter.",
  "Confidence is a skill, not a gift.",
  "Your effort compounds like interest.",
  "Every conversation is a chance to grow.",
  "Be curious, not judgmental.",
  "Small talk builds big bridges.",
  "Empathy is your hidden superpower.",
  "Take the first step; the rest will follow.",
  "Your words can open doors.",
  "Challenges are just skills in disguise.",
  "One skill at a time.",
  "Fail forward and learn faster.",
  "Soft skills create hard results.",
  "Your growth inspires others.",
  "Practice makes confidence.",
  "Be brave enough to start the talk.",
  "You can learn from every interaction.",
  "A smile is your strongest opener.",
  "Listen to understand, not to reply.",
  "Habits build mastery.",
  "It's okay to be a beginner.",
  "Take action, fear will follow.",
  "Skills grow with attention and time.",
  "Your future self will thank you.",
];

const List<String> motivationalTextsSr = [
  "Mali koraci grade veliko samopouzdanje.",
  "Progovori, čak i kad ti glas drhti.",
  "Doslednost pobeđuje motivaciju.",
  "Hrabrost počinje jednim malim korakom.",
  "Rast počinje izvan zone komfora.",
  "Napredak, ne savršenstvo.",
  "Slušaj više, govori pametnije.",
  "Samopouzdanje je veština, ne dar.",
  "Tvoj trud se uvećava kao kamata.",
  "Svaki razgovor je prilika za rast.",
  "Budi radoznao, ne osuđuj.",
  "Mali razgovori grade velike mostove.",
  "Empatija je tvoja skrivena supermoć.",
  "Napravi prvi korak, ostalo će doći.",
  "Tvoje reči mogu da otvore vrata.",
  "Izazovi su samo veštine u prerušenju.",
  "Jedna veština u isto vreme.",
  "Pogreši napred i uči brže.",
  "Meke veštine stvaraju čvrste rezultate.",
  "Tvoj rast inspiriše druge.",
  "Vežbanje gradi samopouzdanje.",
  "Budi dovoljno hrabar da započneš razgovor.",
  "Možeš da naučiš nešto iz svake interakcije.",
  "Osmeh je tvoj najjači uvod.",
  "Slušaj da razumeš, ne da odgovoriš.",
  "Navike grade majstorstvo.",
  "U redu je biti početnik.",
  "Preduzmi akciju, strah će se povući.",
  "Veštine rastu s pažnjom i vremenom.",
  "Tvoje buduće ja će ti zahvaliti.",
];

String getRandomMotivation({bool isEnglish = true}) {
  final list = isEnglish ? motivationalTextsEn : motivationalTextsSr;
  return (list.toList()..shuffle()).first;
}
